# Generated by Django 5.0.6 on 2024-09-21 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gst',
            fields=[
                ('gstid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('gstpercentage', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shopid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('productcode', models.CharField(max_length=300)),
                ('productname', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('stockcount', models.IntegerField()),
                ('purchasingdate', models.DateField()),
                ('purchasingprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.gst')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.shop')),
            ],
        ),
    ]
